FROM node:20 as build

WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY ../client ./

RUN npm install -g @angular/cli
RUN ng build --configuration production


FROM nginx:alpine

COPY --from=build /app/dist/AI-RAG_Chromadb-Project/browser /usr/share/nginx/html

# COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ../deployment/default.conf /etc/nginx/conf.d/default.conf
